### ISSUE TITLE
"salt-minion" service starts while "dumping-salt-minion" is running

### ISSUE THREAD

**Issue by meaksh** [moio/evil-minions#1]
When calling `dumping-salt-minion`, at some point during SUMA onboarding, or in case of a highstate execution, the `salt-minion` service will be automatically started presumably because there are some states definitions where `salt-minion` is set as `service.running`.

This issue would cause extra return events reaching SUSE Manager, and can also produce inconsistencies.

**Comment by moio** [comment]
This is now obsolete as the new architecture does not have `dumping-salt-minion` any more, closing, thanks for reporting anyway.
